name: pre-release

# Refer to https://help.github.com/en/articles/workflow-syntax-for-github-actions for documentation on Actions.
on:
  release:
    types:
      - prereleased

jobs:
  # Generate a static build artifact for usage in deployments.
  assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate release tag
        run: |
          # We only want to run on tags looking like refs/tags/v1200.
          echo "Checking tag: $GITHUB_REF"
          [[ "${GITHUB_REF:10:1}" == "v" ]] || exit 1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.49.0

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: "Build asset"
        uses: ./.github/actions/build-asset
      # NOTE: Artifacts are not available across workflows.
      - uses: actions/upload-artifact@v2
        with:
          name: bootstrap
          path: ./target/cdk/release/bootstrap
          if-no-files-found: error

  benchmark:
    runs-on: ubuntu-latest
    needs: [assets]
    environment:
      name: benchmark

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 14.12.0
        uses: actions/setup-node@v1
        with:
          node-version: "14.12.0"

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-
      - name: "Setup node dependencies"
        uses: ./.github/actions/setup-node-deps

      - uses: actions/download-artifact@v2
        with:
          name: bootstrap
          path: ./target/cdk/release

      - name: Benchmark
        id: benchmark
        if: env.AWS_ACCESS_KEY_ID && env.AWS_SECRET_ACCESS_KEY
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.BENCHMARK_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BENCHMARK_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.BENCHMARK_AWS_REGION }}
          CI: "true"
        run: |
          export BENCHMARK_SUFFIX=$RANDOM
          echo "::set-output name=BENCHMARK_SUFFIX::$BENCHMARK_SUFFIX"
          npm run benchmark

      # Make sure we always clean up even after failing.
      - name: Ensure clean up
        if: failure()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.BENCHMARK_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BENCHMARK_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.BENCHMARK_AWS_REGION }}
          CI: "true"
          BENCHMARK_SUFFIX: ${{ steps.benchmark.outputs.BENCHMARK_SUFFIX }}
        run: |
          npm run benchmark:destroy

      # Only commit the results upon success.
      - name: Commit benchmark results
        if: success()
        uses: codetalkio/add-and-commit@v6
        with:
          author_name: GitHub Actions
          author_email: no-reply@codetalk.io
          message: "Bot: Updating benchmark results"
          add: "./benchmark/*"
          branch: master

  deploy:
    runs-on: ubuntu-latest
    name: "deploy pre-release"
    needs: [assets]
    environment:
      name: staging

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 14.12.0
        uses: actions/setup-node@v1
        with:
          node-version: "14.12.0"

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-
      - name: "Setup node dependencies"
        uses: ./.github/actions/setup-node-deps

      - uses: actions/download-artifact@v2
        with:
          name: bootstrap
          path: ./target/cdk/release

      - name: Deploy
        if: env.AWS_ACCESS_KEY_ID && env.AWS_SECRET_ACCESS_KEY
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PRE_RELEASE_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PRE_RELEASE_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.PRE_RELEASE_AWS_REGION }}
          CI: "true"
        run: |
          npm run cdk:deploy
